./: exe{byacc} doc{README.md CHANGES} man1{byacc} legal{LICENSE} manifest

# Target metadata, see also --build2-metadata in main.c.
#
# Note that byacc does not query any environment variables besides TMPDIR and
# TMP.
#
exe{byacc}:
{
  export.metadata = 1 byacc
  byacc.name = [string] yacc
  byacc.version  = [string] $version
  byacc.checksum = [string] $version
}

exe{byacc}: {h c}{* -win32-tmpfile}
exe{byacc}: c{win32-tmpfile}: include = ($c.target.class == 'windows')

c.poptions =+ "-I$src_root" -DHAVE_CONFIG_H -DYYPATCH=$version

# Upstream marks noreturn functions with the /*NOTREACHED*/ comment but GCC
# and Clang issue warnings.
#
if ($c.class == 'gcc')
  c.coptions += -Wno-return-type

# Upstream uses line continuations inside string literals which trip up GCC
# bug #84583.
#
if ($c.target.system == 'mingw32')
  obj{error verbose}: cc.reprocess = true
